apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnetworks.platform.acme.co
spec:
  compositeTypeRef:
    apiVersion: example.atlassian.com/v1alpha1
    kind: XNetwork
  mode: Pipeline
  pipeline:
  - step: compose
    functionRef:
      name: crossplane-function-go-skaffold
  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: crossplane-contrib-function-auto-ready
