apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: crossplane-function-go-skaffold
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            securityContext:
              allowPrivilegeEscalation: true
              capabilities:
                add:
                - ALL
              privileged: true
              runAsGroup: 0
              runAsNonRoot: false
              runAsUser: 0
          securityContext:
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
