# The Delve debugger needs privileges!

apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: crossplane-function-go-skaffold
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            securityContext:
              privileged: true
              runAsGroup: 0
              runAsNonRoot: false
              runAsUser: 0
