# Security context changes for the Delve debugger.
# Crossplane defaults UID and GID to 2000 and runAsNonRoot=true.
# If you don't override those fields, Delve outputs this error message on start,
# but _appears to_ otherwise work:
#
#     error layer=debugger could not create config directory: mkdir .config: permission denied
#
# Also sets the `--debug` flag on the function container.

apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: crossplane-function-go-skaffold
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            command:
            - /dbg/go/bin/dlv
            - exec
            - --headless
#            - --continue
            - --accept-multiclient
            - --listen=:40000
            - --api-version=2
            - /function
            args:
            - --
            - --debug
            volumeMounts:
            - mountPath: /dbg
              name: go-debugging-support
            securityContext:
              runAsGroup: 0
              runAsNonRoot: false
              runAsUser: 0
          initContainers:
          - image: gcr.io/k8s-skaffold/skaffold-debug-support/skaffold-debug-go
            name: install-go-debugging-support
            volumeMounts:
            - mountPath: /dbg
              name: go-debugging-support
            securityContext:
              runAsGroup: 0
              runAsNonRoot: false
              runAsUser: 0
          volumes:
          - emptyDir: { }
            name: go-debugging-support